name: CI/CD for NestJS

on: 
  push: 
    branches:
      - main
    
  pull_request:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Create PEM file in home directory and set permissions
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > $HOME/ec2-key.pem
          chmod 400 $HOME/ec2-key.pem

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER}}
          EC2_KEY: ${{ secrets.EC2_KEY }}
          run: |
           ssh -o StrictHostKeyChecking=no -i $HOME/ec2-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} cd /home/ubuntu/hello-world-Nest-Js && git pull && npm install && pm2 restart hello-world || pm2 start dist/main.js --name "hello-world"
          

