name: CI/CD for NestJS

on: 
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Create PEM file in home directory and set permissions
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > $HOME/ec2-key.pem
          chmod 400 $HOME/ec2-key.pem

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER}}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/hello-world-Nest-Js
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/Shubhamrahangdale/hello-world-Nest-Js.git
            fi
            git fetch origin
            git reset --hard origin/main
          

